@extends('layouts.admin_layout')

@section('content')
    <div class="dashboard-body">

        <!-- Breadcrumb -->
        <div class="breadcrumb-with-buttons mb-24 flex-between flex-wrap gap-8">
            <div class="breadcrumb mb-24">
                <ul class="flex-align gap-4">
                    <li><a href="{{ url('/') }}" class="text-gray-200 fw-normal text-15 hover-text-main-600">Home</a></li>
                    <li><span class="text-gray-500 fw-normal d-flex"><i class="ph ph-caret-right"></i></span></li>
                    <li><span class="text-main-600 fw-normal text-15">Reports</span></li>
                </ul>
            </div>
            <!-- Export Button (Green) -->
            <div class="d-flex gap-3">
                @if(isset($reports) && $reports->count() > 0)
                    <a href="{{ route('reports.export') }}" class="btn btn-success btn-sm">
                        <i class="ph ph-file-csv me-1"></i> Export Reports (CSV)
                    </a>
                @endif
            </div>

        </div>

        <!-- Report Filter Form -->
        <div class="card mt-24 mb-24">
            <div class="card-body">
                <form id="reportForm" action="{{ route('reports.generate', 'booking') }}" method="POST"
                    class="search-input-form">
                    @csrf
                    <div class="search-input">
                        <select name="report_type" id="reportType"
                            class="form-control form-select h6 rounded-4 mb-0 py-6 px-8"
                            onchange="updateFormAction(this.value)">
                            <option value="" disabled selected>Select Report Type</option>
                            <option value="booking">Booking</option>
                            <option value="guest">Guest</option>
                            <option value="room">Room</option>
                            <option value="payment">Payment</option>
                        </select>
                    </div>
                    <div class="search-input">
                        <input type="date" name="date_from" value="{{ request('date_from') }}"
                            class="form-control h6 rounded-4 mb-0 py-6 px-8" placeholder="From Date">
                    </div>
                    <div class="search-input">
                        <input type="date" name="date_to" value="{{ request('date_to') }}"
                            class="form-control h6 rounded-4 mb-0 py-6 px-8" placeholder="To Date">
                    </div>
                    <div class="search-input">
                        <button type="submit" class="btn btn-main rounded-pill py-9 w-100">Generate</button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Reports Table -->
        <div class="card p-3">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="h6 text-gray-300">#</th>
                        <th class="h6 text-gray-300">Report Type</th>
                        <th class="h6 text-gray-300">Generated By</th>
                        <th class="h6 text-gray-300">Filters</th>
                        <th class="h6 text-gray-300">Created At</th>
                        <th class="h6 text-gray-300">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($reports as $key => $report)
                        <tr>
                            <td class="h6 mb-0 fw-medium text-gray-300">{{ $key + 1 }}</td>
                            <td class="h6 mb-0 fw-medium text-gray-300">{{ ucfirst($report->report_type) }}</td>
                            <td class="h6 mb-0 fw-medium text-gray-300">{{ $report->user?->name ?? 'System' }}</td>
                            <td class="h6 mb-0 fw-medium text-gray-300">
                                @php
                                    $filters = $report->filters ?? [];
                                @endphp

                                @if(isset($filters['date_from']) || isset($filters['date_to']))
                                    {{ isset($filters['date_from']) ? \Carbon\Carbon::parse($filters['date_from'])->format('d M Y') : '---' }}
                                    to
                                    {{ isset($filters['date_to']) ? \Carbon\Carbon::parse($filters['date_to'])->format('d M Y') : '---' }}
                                @else
                                    <span class="text-muted">No Date Filter</span>
                                @endif
                            </td>

                            <td class="h6 mb-0 fw-medium text-gray-300">{{ $report->created_at->format('d M Y, h:i A') }}</td>
                            <td class="h6 mb-0 fw-medium text-gray-300">
                                <a href="{{ route('reports.show', $report->id) }}"
                                    class="bg-main-50 text-main-600 py-2 px-14 rounded-pill hover-bg-main-600 hover-text-white">
                                    View
                                </a>
                                @if($report->file_path)
                                    <a href="{{ asset('storage/' . $report->file_path) }}" target="_blank"
                                        class="bg-success-50 text-success-600 py-2 px-14 rounded-pill hover-bg-success-600 hover-text-white">
                                        Download
                                    </a>
                                @endif
                                <form action="{{ route('reports.destroy', $report->id) }}" method="POST"
                                    style="display:inline;">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit"
                                        class="bg-danger-50 text-danger-600 py-2 px-14 rounded-pill hover-bg-danger-600 hover-text-white"
                                        onclick="return confirm('Are you sure you want to delete this report?')">
                                        Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="text-center text-muted">No reports found</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

    </div>

    <script>
        function updateFormAction(type) {
            const form = document.getElementById('reportForm');
            form.action = "{{ url('/reports/generate') }}/" + type;
        }
    </script>
@endsection