@extends('layouts.admin_layout')

@section('content')
    <div class="dashboard-body">

        <!-- Breadcrumb -->
        <div class="breadcrumb-with-buttons mb-24 flex-between flex-wrap gap-8">
            <div class="breadcrumb mb-24">
                <ul class="flex-align gap-4">
                    <li><a href="{{ route('reports.index') }}"
                            class="text-gray-200 fw-normal text-15 hover-text-main-600">Reports</a></li>
                    <li><span class="text-gray-500 fw-normal d-flex"><i class="ph ph-caret-right"></i></span></li>
                    <li><span class="text-main-600 fw-normal text-15">{{ ucfirst($report->report_type) }} Report</span></li>
                </ul>
            </div>
        </div>

        <!-- Report Details -->
        <div class="card p-4 mb-4">
            <h5 class="mb-3">Report Info</h5>
            <p><strong>Type:</strong> {{ ucfirst($report->report_type) }}</p>
            <p><strong>Generated By:</strong> {{ $report->user?->name ?? 'System' }}</p>
            @php
                $filters = $report->filters ?? [];
            @endphp

            <p><strong>Filters:</strong>
                @if(isset($filters['date_from']) || isset($filters['date_to']))
                    {{ isset($filters['date_from']) ? \Carbon\Carbon::parse($filters['date_from'])->format('d M Y') : '---' }}
                    to
                    {{ isset($filters['date_to']) ? \Carbon\Carbon::parse($filters['date_to'])->format('d M Y') : '---' }}
                @else
                    <span class="text-muted">No Date Filter</span>
                @endif
            </p>
            <p><strong>Created At:</strong> {{ $report->created_at->format('d M Y, h:i A') }}</p>
        </div>

        <!-- Report Data -->
        <div class="card p-4">
            <h5 class="mb-3">Report Data</h5>

            @if($report->data && count($report->data))
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead class="table-light">
                            <tr>
                                @foreach(array_keys($report->data[0]) as $col)
                                    <th>{{ ucfirst(str_replace('_', ' ', $col)) }}</th>
                                @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($report->data as $row)
                                <tr>
                                    @foreach($row as $val)
                                        <td>{{ $val }}</td>
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @else
                <p class="text-muted">No data available for this report.</p>
            @endif
        </div>

    </div>
@endsection